
package com.mycompany.crud.usuariosGUI;

import com.mycompany.crud.usuariosBL.usuariosBL;
import com.mycompany.crud.usuariosDAL.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author laptop
 */
public class FRMregistro extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    public FRMregistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf2passwordconfirm = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf2Name = new javax.swing.JTextField();
        tf2Username = new javax.swing.JTextField();
        tf2LastName = new javax.swing.JTextField();
        tf2Celular = new javax.swing.JTextField();
        tf2Password = new javax.swing.JPasswordField();
        tf2Mail = new javax.swing.JTextField();
        tf2User = new java.awt.Label();
        tf2NameLabel = new java.awt.Label();
        tf2ApellidoLabel = new java.awt.Label();
        tf2CelularLabel = new java.awt.Label();
        tf2Correo = new java.awt.Label();
        tf2Contras = new java.awt.Label();
        tf2ConfirmarContra = new java.awt.Label();
        btnToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        tf2passwordconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2passwordconfirmActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(255, 102, 102));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tabla de Registro");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tf2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2NameActionPerformed(evt);
            }
        });

        tf2Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2UsernameActionPerformed(evt);
            }
        });

        tf2Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2CelularActionPerformed(evt);
            }
        });

        tf2Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2PasswordActionPerformed(evt);
            }
        });

        tf2User.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2User.setForeground(new java.awt.Color(255, 255, 255));
        tf2User.setText("Usuario");

        tf2NameLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        tf2NameLabel.setText("Nombre");

        tf2ApellidoLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2ApellidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        tf2ApellidoLabel.setText("Apellido");

        tf2CelularLabel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2CelularLabel.setForeground(new java.awt.Color(255, 255, 255));
        tf2CelularLabel.setText("Celular");

        tf2Correo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2Correo.setForeground(new java.awt.Color(255, 255, 255));
        tf2Correo.setText("Correo");

        tf2Contras.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2Contras.setForeground(new java.awt.Color(255, 255, 255));
        tf2Contras.setText("Contraseña");

        tf2ConfirmarContra.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tf2ConfirmarContra.setForeground(new java.awt.Color(255, 255, 255));
        tf2ConfirmarContra.setText("Confirmar");

        btnToLogin.setBackground(new java.awt.Color(255, 102, 102));
        btnToLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnToLogin.setText("Atrás");
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf2NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2ApellidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2ConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2Contras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2CelularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf2Celular)
                            .addComponent(tf2LastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2Username, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tf2Password, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf2passwordconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(320, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf2User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf2Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(tf2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf2NameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2ApellidoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf2LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2CelularLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf2Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf2Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2Password)
                            .addComponent(tf2Contras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf2ConfirmarContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf2passwordconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegister)
                            .addComponent(btnToLogin))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2passwordconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2passwordconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2passwordconfirmActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username = tf2Username.getText();
        String password = tf2Password.getText();
        String passwordConfirm = tf2passwordconfirm.getText();
        String lastName = tf2LastName.getText();
        String mail = tf2Mail.getText();
        String name = tf2Name.getText();
        String celular = tf2Celular.getText();
        
        Conexion objConexion = new Conexion();
        
        usuariosBL oUsuarios = recuperarDatosGUI();
        
        String strSentencInsert = String.format("insert INTO persona(Id, UserName, Nombre, Apellido, Celular, Correo, Contraseña, ConfirContra) "
                + "values(null, '%s', '%s', '%s', '%s', '%s', '%s', '*******')", oUsuarios.getUsuario(), oUsuarios.getNombre(), oUsuarios.getApellido(), oUsuarios.getCelular(), oUsuarios.getCorreo(), oUsuarios.getContraseña());
        
        objConexion.ejecutarsentenciaSQL(strSentencInsert);
       
       
        
        if(password == null ? passwordConfirm == null  : password.equals(passwordConfirm)) {} 
        else{
            
            JOptionPane.showMessageDialog(this, "La contraseña debe de ser igual en ambos campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Nombre", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        if(lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Apellido", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        
        if(celular.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Celular", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
         if(mail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Correo", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        if(password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(passwordConfirm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe de confirmar la Contraseña", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        
        if(passwordConfirm.isEmpty() || password.isEmpty() || mail.isEmpty() || celular.isEmpty() || lastName.isEmpty() || name.isEmpty() || username.isEmpty() ||  (password == null ? passwordConfirm != null : !password.equals(passwordConfirm)) )  {
           
        } else{
        FRMlogin vueltaLogin = new FRMlogin();
        
        vueltaLogin.setVisible(true) ;
        dispose();
                
        }
        //start the login process.
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tf2UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2UsernameActionPerformed

    private void tf2CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2CelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2CelularActionPerformed

    private void tf2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2NameActionPerformed

    private void tf2PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2PasswordActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed

        
        FRMlogin vueltaLogin = new FRMlogin();
        
        vueltaLogin.setVisible(true) ;
        dispose();

    }//GEN-LAST:event_btnToLoginActionPerformed

    
    public usuariosBL recuperarDatosGUI() {
        usuariosBL oUsuarios = new usuariosBL();
        
        
        oUsuarios.setUsuario(tf2Username.getText());
        oUsuarios.setContraseña(tf2Password.getText());
        oUsuarios.setCorreo(tf2Mail.getText());
        oUsuarios.setCelular(tf2Celular.getText());
        oUsuarios.setNombre(tf2Name.getText());
        oUsuarios.setApellido(tf2LastName.getText());
       
        return oUsuarios;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMregistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private java.awt.Label tf2ApellidoLabel;
    private javax.swing.JTextField tf2Celular;
    private java.awt.Label tf2CelularLabel;
    private java.awt.Label tf2ConfirmarContra;
    private java.awt.Label tf2Contras;
    private java.awt.Label tf2Correo;
    private javax.swing.JTextField tf2LastName;
    private javax.swing.JTextField tf2Mail;
    private javax.swing.JTextField tf2Name;
    private java.awt.Label tf2NameLabel;
    private javax.swing.JPasswordField tf2Password;
    private java.awt.Label tf2User;
    private javax.swing.JTextField tf2Username;
    private javax.swing.JPasswordField tf2passwordconfirm;
    // End of variables declaration//GEN-END:variables
}
