
package com.mycompany.crud.usuariosGUI;
import com.mycompany.crud.usuariosBL.usuariosBL;
import com.mycompany.crud.usuariosDAL.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FRMusuarios extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public FRMusuarios() {
        initComponents();
        
        String [] titulos = {"ID", "Usuario", "Contraseña", "Nombre" ,"Apellido", "Celular", "Correo", };
        model = new DefaultTableModel(null, titulos);
        tblUsuarios.setModel(model);
        
        this.mostrarDatos();
        this.limpiar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnAgregar = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lbContra = new javax.swing.JLabel();
        btnCancelar = new java.awt.Button();
        label3 = new java.awt.Label();
        btnBorrar = new java.awt.Button();
        btnEditar = new java.awt.Button();
        txtID = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(0, 0, 51));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setLabel("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 70, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        jPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 710, 130));

        lbContra.setForeground(new java.awt.Color(255, 255, 255));
        lbContra.setText("Contraseña");
        jPanel.add(lbContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 70, -1));

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Usuario");
        jPanel.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnBorrar.setLabel("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 70, -1));

        btnEditar.setLabel("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 70, -1));

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));
        jPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));
        jPanel.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        jPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));
        jPanel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 180, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 180, -1));
        jPanel.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 180, -1));
        jPanel.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        jPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 60, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\laptop\\OneDrive\\Escritorio\\New folder\\agregar verdes.png")); // NOI18N
        jPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 130, 140));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Celular");
        jPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 50, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");
        jPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here
        Conexion objConexion = new Conexion();
        
        usuariosBL oUsuarios = recuperarDatosGUI();
        
        String strSentencInsert = String.format("insert INTO persona(Id, UserName, Nombre, Apellido, Celular, Correo, Contraseña, ConfirContra) "
                + "values(null, '%s', '%s', '%s', '%s', '%s', '%s', '*******')", oUsuarios.getUsuario(), oUsuarios.getNombre(), oUsuarios.getApellido(), oUsuarios.getCelular(), oUsuarios.getCorreo(), oUsuarios.getContraseña());
        
        objConexion.ejecutarsentenciaSQL(strSentencInsert);
       
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()==1){
        JTable receptor = (JTable) evt.getSource();
        
        txtID.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),0));
        txtUsuario.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),1));
        txtContra.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),2));
        txtNombre.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),3));
        txtApellido.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),4));
        txtCelular.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),5));
        txtCorreo.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(),6));
        }
        btnAgregar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnBorrar.setEnabled(true);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
          Conexion objConexion = new Conexion();
        
        usuariosBL oUsuarios = recuperarDatosGUI();
        
        String strSentencInsert = String.format("DELETE FROM persona WHERE Id=%d",oUsuarios.getID());
        
        objConexion.ejecutarsentenciaSQL(strSentencInsert);
        
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
          Conexion objConexion = new Conexion();
        
        usuariosBL oUsuarios = recuperarDatosGUI();
        
        String strSentencInsert;
        strSentencInsert = String.format("UPDATE persona SET UserName = '%s'," + "Contraseña = '%s'," + "Nombre = '%s'," + "Apellido = '%s'," + "Celular ='%s' ," + 
                "Correo = '%s' WHERE Id = %d " , oUsuarios.getUsuario(), oUsuarios.getContraseña(), oUsuarios.getNombre(), oUsuarios.getApellido(), oUsuarios.getCelular(), oUsuarios.getCorreo(), oUsuarios.getID());
        
        objConexion.ejecutarsentenciaSQL(strSentencInsert);
       
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        this.limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        
        FRMlogin cerrarToLogin1 = new FRMlogin();
        
        cerrarToLogin1.setVisible(true) ;
        dispose();
        
    }//GEN-LAST:event_btnCerrarActionPerformed
    public void mostrarDatos() {
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
                
                
        Conexion objConexion = new Conexion();
        
        try {
        ResultSet resultado = objConexion.consultarRegistro("SELECT*FROM persona");
        
        while (resultado.next()) {
            System.out.println(resultado.getString("Id"));
            System.out.println(resultado.getString("UserName"));
            System.out.println(resultado.getString("Nombre"));
            System.out.println(resultado.getString("Apellido"));
            System.out.println(resultado.getString("Celular"));
            System.out.println(resultado.getString("Correo"));
            
            Object[] oUsers ={resultado.getString("Id"), resultado.getString("UserName"),
                resultado.getString("Contraseña"), resultado.getString("Nombre") ,resultado.getString("Apellido"), resultado.getString("Celular"),
            resultado.getString("Correo")};
            
            model.addRow(oUsers);
        }
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        
        
    }
    public usuariosBL recuperarDatosGUI() {
        usuariosBL oUsuarios = new usuariosBL();
        int ID = (txtID.getText().isEmpty())?0: Integer.parseInt(txtID.getText());
        oUsuarios.setID(ID);
        oUsuarios.setUsuario(txtUsuario.getText());
        oUsuarios.setContraseña(txtContra.getText());
        oUsuarios.setCorreo(txtCorreo.getText());
        oUsuarios.setCelular(txtCelular.getText());
        oUsuarios.setNombre(txtNombre.getText());
        oUsuarios.setApellido(txtApellido.getText());
        return oUsuarios;
    }
    
    public void limpiar(){
        
        txtID.setText("");
        txtUsuario.setText("");
        txtContra.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        
        btnAgregar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnBorrar.setEnabled(false);
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMusuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAgregar;
    private java.awt.Button btnBorrar;
    private java.awt.Button btnCancelar;
    private javax.swing.JButton btnCerrar;
    private java.awt.Button btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label3;
    private javax.swing.JLabel lbContra;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
